# fly.toml app configuration file generated for advisory-travel on 2023-09-25T14:40:25-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "advisory-travel"
primary_region = "iad"
console_command = "/rails/bin/rails console"

[build]

[processes]
  app = "bin/rails server"
  worker = "bundle exec sidekiq"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  processes = ["app"]

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
