:concurrency: 3
:timeout: 60
:verbose: true
:queues:
  # Queue priority:
  # https://github.com/mperham/sidekiq/wiki/Advanced-Options
  # https://mikerogers.io/2019/06/06/rails-6-sidekiq-queues
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge
:scheduler:
  :schedule:
    get_US_advisories_job:
      cron: '0 */12 * * *'   # Runs every 12 hours
      class: GetUsAdvisoriesJob
